CREATE TABLE IF NOT EXISTS users
(
    Id                     TEXT PRIMARY KEY,
    Email                  TEXT UNIQUE NOT NULL,
    Password               TEXT        NOT NULL,
    AccessToken            TEXT,
    RefreshToken           TEXT,
    Verified               BOOLEAN   DEFAULT FALSE,
    LastResetSentAt        TEXT,
    LastVerificationSentAt TEXT,
    Roles                  TEXT,
    CreatedAt              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles
(
    Id        TEXT PRIMARY KEY,
    Name      TEXT,
    Avatar    TEXT,
    UserId    TEXT UNIQUE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profiles_users FOREIGN KEY (UserId) REFERENCES users (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS categories
(
    Id        TEXT PRIMARY KEY,
    Name      TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS farms
(
    Id         TEXT PRIMARY KEY,
    Name       TEXT        NOT NULL,
    CategoryId TEXT UNIQUE NOT NULL,
    UserId     TEXT UNIQUE NOT NULL,
    CreatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_farms_users FOREIGN KEY (UserId) REFERENCES users (Id),
    CONSTRAINT fk_farms_categories FOREIGN KEY (CategoryId) REFERENCES categories (Id)
);

CREATE TABLE IF NOT EXISTS purchases
(
    Id          TEXT PRIMARY KEY,
    Name        TEXT        NOT NULL,
    Description TEXT,
    Quantity    INTEGER,
    Attachment  TEXT,
    FarmId      TEXT UNIQUE NOT NULL,
    CreatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchases_farms FOREIGN KEY (FarmId) REFERENCES farms (Id)
);

CREATE TABLE IF NOT EXISTS orders
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS locations
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS providers
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activities
(
    Id        TEXT PRIMARY KEY,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

